---
title: "Senior Project Random Forest"
author: "Michael Streyle"
date: "October 30th, 2018"
output: word_document
editor_options: 
chunk_output_type: console
---
  
```{r echo=F}
knitr::opts_chunk$set(comment=NA, message=FALSE, echo=FALSE, warning = FALSE)
```

# Introduction

```{r}

setwd("C:/Users/Michael Streyle/Desktop/Senior Project") #change this when i switch computers
#setwd("C:/Users/Michael/Desktop/Senior Project")

data1  <- read.csv('Dataset_spine.csv', col.names = c('pelvic_incidence', 'pelvic_tilt', 'lumbar_lordosis_angle', 'sacral_slope', 'pelvic_radius', 'degree_spondylolisthesis', 'pelvic_slope', 'Direct_tilt', 'thoracic_slope', 'cervical_tilt', 'sacrum_angle', 'scoliosis_slope', 'classification', ' '))


data1$X. <- NULL #dropping the column with variable descriptions in it



data = scale(data1[, 1:12]) #scaling all except classification variable
data = data.frame(data)
data$classification = data1$classification #add classification back into scaled dataframe
data$class = ifelse(data$classification == "Abnormal", 0, 1) #making classification numeric

#these are the packages I use:

# library(ModelMetrics) old use for confusion matrices. wasnt working for factor columns
library(e1071) #SVM
library(randomForest)
library(caret) #for confusion matrices

attach(data)


```


# Initial Model



```{r}
#make train and test set
smp_size <- floor(0.8 * nrow(data))
set.seed(12)
train_ind <- sample(seq_len(nrow(data)), size = smp_size)
rf_train <- data[train_ind, ]
rf_test <- data[-train_ind, ]


random_forest = randomForest(classification ~ pelvic_tilt + pelvic_incidence + lumbar_lordosis_angle + sacral_slope + pelvic_radius + degree_spondylolisthesis, data = rf_train)

#importance of variables
importance(random_forest)
varImpPlot(random_forest,type=2)

pred = predict(random_forest, rf_test)
rf_test$rf_pred = pred

rf_cf = caret::confusionMatrix(rf_test$classification, rf_test$rf_pred)
rf_cf

#accuracy score is now in the output of the classification matrix. 

im = tuneRF(x = rf_train[,1:6], y = rf_train[,13], doBest = T)
im

importance(im)
varImpPlot(im,type=2)


```

# Cross-Validation Model



```{r}
data$rand_int = runif(n=nrow(data), min = 0, max = 1) #random values from uniform distribution
data2 = data[order(data$rand_int),] #reorder dataframe by random value

data2$group = seq(from = 1, to=5, by=1)
data2$pred_ranfor = 0
data2$pred_class = as.factor(x = c("Abnormal", "Normal"))
attach(data2)



im_cv = tuneRF(x = data2[,1:6], y = data2[,13])
im_cv


for (grp in 1:5){
  train = data2[data2$group != grp, ]
  test = data2[data2$group == grp,]
  
  cv_ranfor <- randomForest(classification ~ pelvic_tilt + pelvic_incidence + lumbar_lordosis_angle + 
                     sacral_slope + pelvic_radius + degree_spondylolisthesis, data = train,                              mtry=2)

  pred_ranfor = predict(object = cv_ranfor, test, "prob")[,"Normal"]
  data2$pred_ranfor[data2$group == grp] = pred_ranfor
  
  pred_class = predict(object = cv_ranfor, test)
  data2$pred_class[data2$group == grp] = pred_class
}

importance(random_forest)
varImpPlot(random_forest,type=2)

cv_ranfor_cf = caret::confusionMatrix( data2$classification, data2$pred_class)
cv_ranfor_cf

plot(y=data2$class, x=data2$pred_ranfor, main = "Probability vs Class for Tuned CV RF", xlab = "Predicted Probability of Normal", ylab="Class (0=Abnormal, 1=Normal)")
lines(lowess(y = data2$class, x=data2$pred_ranfor))




```


# Add Provided Random Noise


```{r}
set.seed(12)
df  <- read.csv('Dataset_spine.csv', col.names = c('pelvic_incidence', 'pelvic_tilt', 'lumbar_lordosis_angle', 'sacral_slope', 'pelvic_radius', 'degree_spondylolisthesis', 'pelvic_slope', 'Direct_tilt', 'thoracic_slope', 'cervical_tilt', 'sacrum_angle', 'scoliosis_slope', 'classification', ' '))

df$class = ifelse(df$classification == "Abnormal", 0, 1) #making classification numeric
df$X. <- NULL #dropping the column with variable descriptions in it
data = scale(df[, 1:12]) #scaling all except classification variable
data = data.frame(data)
data$classification = data1$classification #add classification back into scaled dataframe
data$class = data1$class

data$rand_int = runif(n=nrow(data), min = 0, max = 1) #random values from uniform distribution
data2 = data[order(data$rand_int),] #reorder dataframe by random value


data2$group = seq(from = 1, to=5, by=1)
data2$pred_ranfor = 0
data2$pred_class = as.factor(x = c("Abnormal", "Normal"))
attach(data2)



im_cv = tuneRF(x = data2[,1:12], y = data2[,13])
im_cv


for (grp in 1:5){
  train = data2[data2$group != grp, ]
  test = data2[data2$group == grp,]
  
  cv_ranfor <- randomForest(classification ~ . - group - rand_int - class - pred_ranfor - pred_class, data = train,                              mtry=2)

  pred_ranfor = predict(object = cv_ranfor, test, "prob")[,"Normal"]
  data2$pred_ranfor[data2$group == grp] = pred_ranfor
  
  pred_class = predict(object = cv_ranfor, test)
  data2$pred_class[data2$group == grp] = pred_class
}

importance(cv_ranfor)
varImpPlot(cv_ranfor,type=2)

cv_ranfor_cf_wpn = caret::confusionMatrix( data2$classification, data2$pred_class)
cv_ranfor_cf_wpn

plot(y=data2$class, x=data2$pred_ranfor, main = "Probability vs Class for Tuned CV w/PRN RF", xlab = "Predicted Probability of Normal", ylab="Class (0=Abnormal, 1=Normal)")
lines(lowess(y = data2$class, x=data2$pred_ranfor))

```

# Add 10 Random Variables



```{r}
df  <- read.csv('Dataset_spine.csv', col.names = c('pelvic_incidence', 'pelvic_tilt', 'lumbar_lordosis_angle', 'sacral_slope', 'pelvic_radius', 'degree_spondylolisthesis', 'pelvic_slope', 'Direct_tilt', 'thoracic_slope', 'cervical_tilt', 'sacrum_angle', 'scoliosis_slope', 'classification', ' '))
set.seed(12)
df$class = ifelse(df$classification == "Abnormal", 0, 1)
df$X. <- NULL #dropping the column with variable descriptions in it
data = scale(df[, 1:12]) #scaling all except classification variable
data = data.frame(data)
data$classification = df$classification #add classification back into scaled dataframe
data$class = df$class

rand_df = data.frame(matrix(rnorm(10*nrow(data)), nrow = nrow(data), ncol = 10))
data = cbind(data, rand_df)
#write.csv(x = data, file = "data_with10.csv")



data$rand_int = runif(n=nrow(data), min = 0, max = 1) #random values from uniform distribution
data2 = data[order(data$rand_int),] #reorder dataframe by random value


data2$group = seq(from = 1, to=5, by=1)
data2$pred_ranfor = 0
data2$pred_class = as.factor(x = c("Abnormal", "Normal"))
attach(data2)



im_cv = tuneRF(x = data2[,c(1:12,15:24)], y = data2[,13])
im_cv


for (grp in 1:5){
  train = data2[data2$group != grp, ]
  test = data2[data2$group == grp,]
  
  cv_ranfor <- randomForest(classification ~ . - group - rand_int - class - pred_ranfor - pred_class, data = train,                              mtry=16)

  pred_ranfor = predict(object = cv_ranfor, test, "prob")[,"Normal"]
  data2$pred_ranfor[data2$group == grp] = pred_ranfor
  
  pred_class = predict(object = cv_ranfor, test)
  data2$pred_class[data2$group == grp] = pred_class
}

importance(cv_ranfor)
varImpPlot(cv_ranfor,type=2)

cv_ranfor_cf_10 = caret::confusionMatrix( data2$classification, data2$pred_class)
cv_ranfor_cf_10

plot(y=data2$class, x=data2$pred_ranfor, main = "Probability vs Class for Tuned CV w/10 RF", xlab = "Predicted Probability of Normal", ylab="Class (0=Abnormal, 1=Normal)")
lines(lowess(y = data2$class, x=data2$pred_ranfor))


```
# Add 100 Random Variables


```{r}
df  <- read.csv('Dataset_spine.csv', col.names = c('pelvic_incidence', 'pelvic_tilt', 'lumbar_lordosis_angle', 'sacral_slope', 'pelvic_radius', 'degree_spondylolisthesis', 'pelvic_slope', 'Direct_tilt', 'thoracic_slope', 'cervical_tilt', 'sacrum_angle', 'scoliosis_slope', 'classification', ' '))
set.seed(12)
df$class = ifelse(df$classification == "Abnormal", 0, 1)
df$X. <- NULL #dropping the column with variable descriptions in it
data = scale(df[, 1:12]) #scaling all except classification variable
data = data.frame(data)
data$classification = df$classification #add classification back into scaled dataframe
data$class = df$class

rand_df = data.frame(matrix(rnorm(100*nrow(data)), nrow = nrow(data), ncol = 100))
data = cbind(data, rand_df)
#write.csv(x = data, file = "data_with100.csv")



data$rand_int = runif(n=nrow(data), min = 0, max = 1) #random values from uniform distribution
data2 = data[order(data$rand_int),] #reorder dataframe by random value


data2$group = seq(from = 1, to=5, by=1)
data2$pred_ranfor = 0
data2$pred_class = as.factor(x = c("Abnormal", "Normal"))
attach(data2)


im_cv = tuneRF(x = data2[,c(1:12,15:114)], y = data2[,13])
im_cv


for (grp in 1:5){
  train = data2[data2$group != grp, ]
  test = data2[data2$group == grp,]
  
  cv_ranfor <- randomForest(classification ~ . - group - rand_int - class - pred_ranfor - pred_class, data = train,                              mtry=10)

  pred_ranfor = predict(object = cv_ranfor, test, "prob")[,"Normal"]
  data2$pred_ranfor[data2$group == grp] = pred_ranfor
  
  pred_class = predict(object = cv_ranfor, test)
  data2$pred_class[data2$group == grp] = pred_class
}

importance(cv_ranfor)
varImpPlot(cv_ranfor,type=2)

cv_ranfor_cf_100 = caret::confusionMatrix( data2$classification, data2$pred_class)
cv_ranfor_cf_100

plot(y=data2$class, x=data2$pred_ranfor, main = "Probability vs Class for Tuned CV w/100 RF", xlab = "Predicted Probability of Normal", ylab="Class (0=Abnormal, 1=Normal)")
lines(lowess(y = data2$class, x=data2$pred_ranfor))

```

# Add 500 Random Variables



```{r}

df  <- read.csv('Dataset_spine.csv', col.names = c('pelvic_incidence', 'pelvic_tilt', 'lumbar_lordosis_angle', 'sacral_slope', 'pelvic_radius', 'degree_spondylolisthesis', 'pelvic_slope', 'Direct_tilt', 'thoracic_slope', 'cervical_tilt', 'sacrum_angle', 'scoliosis_slope', 'classification', ' '))
set.seed(12)
df$class = ifelse(df$classification == "Abnormal", 0, 1)
df$X. <- NULL #dropping the column with variable descriptions in it
data = scale(df[, 1:12]) #scaling all except classification variable
data = data.frame(data)
data$classification = df$classification #add classification back into scaled dataframe
data$class = df$class

rand_df = data.frame(matrix(rnorm(500*nrow(data)), nrow = nrow(data), ncol = 500))
data = cbind(data, rand_df)
#write.csv(x = data, file = "data_with500.csv")



data$rand_int = runif(n=nrow(data), min = 0, max = 1) #random values from uniform distribution
data2 = data[order(data$rand_int),] #reorder dataframe by random value


data2$group = seq(from = 1, to=5, by=1)
data2$pred_ranfor = 0
data2$pred_class = as.factor(x = c("Abnormal", "Normal"))
attach(data2)


im_cv = tuneRF(x = data2[,c(1:12,15:514)], y = data2[,13])
im_cv


for (grp in 1:5){
  train = data2[data2$group != grp, ]
  test = data2[data2$group == grp,]
  
  cv_ranfor <- randomForest(classification ~ . - group - rand_int - class - pred_ranfor - pred_class, data = train,                              mtry=176)

  pred_ranfor = predict(object = cv_ranfor, test, "prob")[,"Normal"]
  data2$pred_ranfor[data2$group == grp] = pred_ranfor
  
  pred_class = predict(object = cv_ranfor, test)
  data2$pred_class[data2$group == grp] = pred_class
}

importance(cv_ranfor)
varImpPlot(cv_ranfor,type=2)

cv_ranfor_cf_500 = caret::confusionMatrix( data2$classification, data2$pred_class)
cv_ranfor_cf_500

plot(y=data2$class, x=data2$pred_ranfor, main = "Probability vs Class for Tuned CV w/500 RF", xlab = "Predicted Probability of Normal", ylab="Class (0=Abnormal, 1=Normal)")
lines(lowess(y = data2$class, x=data2$pred_ranfor))


```



# Add 1000 Random Variables



```{r}
df  <- read.csv('Dataset_spine.csv', col.names = c('pelvic_incidence', 'pelvic_tilt', 'lumbar_lordosis_angle', 'sacral_slope', 'pelvic_radius', 'degree_spondylolisthesis', 'pelvic_slope', 'Direct_tilt', 'thoracic_slope', 'cervical_tilt', 'sacrum_angle', 'scoliosis_slope', 'classification', ' '))
set.seed(12)
df$class = ifelse(df$classification == "Abnormal", 0, 1)
df$X. <- NULL #dropping the column with variable descriptions in it
data = scale(df[, 1:12]) #scaling all except classification variable
data = data.frame(data)
data$classification = df$classification #add classification back into scaled dataframe
data$class = df$class

rand_df = data.frame(matrix(rnorm(1000*nrow(data)), nrow = nrow(data), ncol = 1000))
data = cbind(data, rand_df)
#write.csv(x = data, file = "data_with1000.csv")



data$rand_int = runif(n=nrow(data), min = 0, max = 1) #random values from uniform distribution
data2 = data[order(data$rand_int),] #reorder dataframe by random value

data2$group = seq(from = 1, to=5, by=1)
data2$pred_ranfor = 0
data2$pred_class = as.factor(x = c("Abnormal", "Normal"))
attach(data2)


im_cv = tuneRF(x = data2[,c(1:12,15:1014)], y = data2[,13])
im_cv


for (grp in 1:5){
  train = data2[data2$group != grp, ]
  test = data2[data2$group == grp,]
  
  cv_ranfor <- randomForest(classification ~ . - group - rand_int - class - pred_ranfor - pred_class, data = train,                              mtry=31)

  pred_ranfor = predict(object = cv_ranfor, test, "prob")[,"Normal"]
  data2$pred_ranfor[data2$group == grp] = pred_ranfor
  
  pred_class = predict(object = cv_ranfor, test)
  data2$pred_class[data2$group == grp] = pred_class
}

importance(cv_ranfor)
varImpPlot(cv_ranfor,type=2)

cv_ranfor_cf_1000 = caret::confusionMatrix( data2$classification, data2$pred_class)
cv_ranfor_cf_1000

plot(y=data2$class, x=data2$pred_ranfor, main = "Probability vs Class for Tuned CV w/1000 RF", xlab = "Predicted Probability of Normal", ylab="Class (0=Abnormal, 1=Normal)")
lines(lowess(y = data2$class, x=data2$pred_ranfor))


```



